/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos_software_systems;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 *
 * @author Jovy
 */
public class View_POS extends javax.swing.JFrame {
    

    /**
     * Creates new form View_POS
     */
    public View_POS() {
        initComponents();
        
       //Automatically adjusts the system's maximum screen size
        Toolkit centerWindowTool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(centerWindowTool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setSize(width, height);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        Panel_Parent = new javax.swing.JPanel();
        Panel_Buttons = new javax.swing.JPanel();
        btn_Menu = new javax.swing.JButton();
        btn_Drinks = new javax.swing.JButton();
        btn_Extras = new javax.swing.JButton();
        btn_Checkout = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Panel_Cards = new javax.swing.JPanel();
        Card_Admin = new javax.swing.JPanel();
        Card_FoodMenu = new javax.swing.JPanel();
        btn_Burgers = new javax.swing.JButton();
        btn_Sides = new javax.swing.JButton();
        btn_Wings = new javax.swing.JButton();
        btn_Sandwiches = new javax.swing.JButton();
        btn_Wraps = new javax.swing.JButton();
        lbl_FoodMenu = new javax.swing.JLabel();
        btn_KidsMenu = new javax.swing.JButton();
        Card_Drinks = new javax.swing.JPanel();
        btn_FountainDrinks = new javax.swing.JButton();
        btn_SweetTea = new javax.swing.JButton();
        btn_Coffee = new javax.swing.JButton();
        btn_Milkshake = new javax.swing.JButton();
        btn_ChocDrink = new javax.swing.JButton();
        btn_Lemonade = new javax.swing.JButton();
        lbl_DrinksMenu = new javax.swing.JLabel();
        Panel_DrinkSize = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Card_Extras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Card_CheckOut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Debit = new javax.swing.JButton();
        btn_GiftCard = new javax.swing.JButton();
        btn_Credit = new javax.swing.JButton();
        btn_Cash = new javax.swing.JButton();
        Card_Burgers = new javax.swing.JPanel();
        btn_item1 = new javax.swing.JButton();
        btn_item2 = new javax.swing.JButton();
        btn_item3 = new javax.swing.JButton();
        btn_item7 = new javax.swing.JButton();
        btn_item6 = new javax.swing.JButton();
        btn_item4 = new javax.swing.JButton();
        btn_item5 = new javax.swing.JButton();
        lbl_Burgers = new javax.swing.JLabel();
        Panel_Employee_works = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_Order = new javax.swing.JList();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2000, 2500));

        Panel_Background.setBackground(new java.awt.Color(0, 0, 0));

        Panel_Parent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Buttons.setBackground(new java.awt.Color(153, 153, 255));
        Panel_Buttons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_Menu.setBackground(new java.awt.Color(255, 255, 204));
        btn_Menu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Menu.setText("Food");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        btn_Drinks.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        btn_Drinks.setText("Drinks");
        btn_Drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DrinksActionPerformed(evt);
            }
        });

        btn_Extras.setFont(btn_Extras.getFont().deriveFont(btn_Extras.getFont().getSize()+8f));
        btn_Extras.setText("Extras");
        btn_Extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExtrasActionPerformed(evt);
            }
        });

        btn_Checkout.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        btn_Checkout.setText("Checkout");
        btn_Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckoutActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        jButton12.setText("Cancel Order");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ButtonsLayout = new javax.swing.GroupLayout(Panel_Buttons);
        Panel_Buttons.setLayout(Panel_ButtonsLayout);
        Panel_ButtonsLayout.setHorizontalGroup(
            Panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ButtonsLayout.createSequentialGroup()
                .addComponent(btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Drinks, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Extras, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_ButtonsLayout.setVerticalGroup(
            Panel_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Drinks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Extras, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_Parent.add(Panel_Buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 916, 1860, 63));

        Panel_Cards.setBackground(new java.awt.Color(0, 153, 102));
        Panel_Cards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout Card_AdminLayout = new javax.swing.GroupLayout(Card_Admin);
        Card_Admin.setLayout(Card_AdminLayout);
        Card_AdminLayout.setHorizontalGroup(
            Card_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1530, Short.MAX_VALUE)
        );
        Card_AdminLayout.setVerticalGroup(
            Card_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        Panel_Cards.add(Card_Admin, "card7");

        Card_FoodMenu.setBackground(new java.awt.Color(255, 255, 204));
        Card_FoodMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_Burgers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Burgers.setText("Burgers");
        btn_Burgers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BurgersActionPerformed(evt);
            }
        });

        btn_Sides.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Sides.setText("Sides");
        btn_Sides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SidesActionPerformed(evt);
            }
        });

        btn_Wings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Wings.setText("Wings");

        btn_Sandwiches.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Sandwiches.setText("Sandwiches");

        btn_Wraps.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Wraps.setText("Wraps");

        lbl_FoodMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_FoodMenu.setText("Food Menu");

        btn_KidsMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_KidsMenu.setText("Kids' Menu");

        javax.swing.GroupLayout Card_FoodMenuLayout = new javax.swing.GroupLayout(Card_FoodMenu);
        Card_FoodMenu.setLayout(Card_FoodMenuLayout);
        Card_FoodMenuLayout.setHorizontalGroup(
            Card_FoodMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_FoodMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Card_FoodMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_FoodMenu)
                    .addGroup(Card_FoodMenuLayout.createSequentialGroup()
                        .addComponent(btn_Burgers, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btn_Sandwiches, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_Wings, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Card_FoodMenuLayout.createSequentialGroup()
                        .addComponent(btn_Sides, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btn_Wraps, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_KidsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(335, 335, 335))
        );
        Card_FoodMenuLayout.setVerticalGroup(
            Card_FoodMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_FoodMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_FoodMenu)
                .addGap(16, 16, 16)
                .addGroup(Card_FoodMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Burgers, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sandwiches, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Wings, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(Card_FoodMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Sides, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Wraps, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_KidsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Panel_Cards.add(Card_FoodMenu, "card4");

        Card_Drinks.setBackground(new java.awt.Color(255, 255, 204));
        Card_Drinks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_FountainDrinks.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_FountainDrinks.setText("Fountain Drinks");
        btn_FountainDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FountainDrinksActionPerformed(evt);
            }
        });

        btn_SweetTea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_SweetTea.setText("Sweet Tea");
        btn_SweetTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SweetTeaActionPerformed(evt);
            }
        });

        btn_Coffee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Coffee.setText("Coffee");
        btn_Coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CoffeeActionPerformed(evt);
            }
        });

        btn_Milkshake.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Milkshake.setText("MilkShake");
        btn_Milkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MilkshakeActionPerformed(evt);
            }
        });

        btn_ChocDrink.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_ChocDrink.setText("Chocolate Drink");
        btn_ChocDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChocDrinkActionPerformed(evt);
            }
        });

        btn_Lemonade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Lemonade.setText("Lemonade");
        btn_Lemonade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LemonadeActionPerformed(evt);
            }
        });

        lbl_DrinksMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_DrinksMenu.setText("Drinks Menu");

        Panel_DrinkSize.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("REG");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("LARGE");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("KIDS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Size");

        javax.swing.GroupLayout Panel_DrinkSizeLayout = new javax.swing.GroupLayout(Panel_DrinkSize);
        Panel_DrinkSize.setLayout(Panel_DrinkSizeLayout);
        Panel_DrinkSizeLayout.setHorizontalGroup(
            Panel_DrinkSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrinkSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DrinkSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(Panel_DrinkSizeLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_DrinkSizeLayout.setVerticalGroup(
            Panel_DrinkSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DrinkSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(Panel_DrinkSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        Panel_DrinkSizeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        javax.swing.GroupLayout Card_DrinksLayout = new javax.swing.GroupLayout(Card_Drinks);
        Card_Drinks.setLayout(Card_DrinksLayout);
        Card_DrinksLayout.setHorizontalGroup(
            Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_DrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_DrinkSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Card_DrinksLayout.createSequentialGroup()
                        .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DrinksMenu)
                            .addGroup(Card_DrinksLayout.createSequentialGroup()
                                .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_FountainDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_SweetTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Milkshake)
                                    .addComponent(btn_ChocDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Lemonade)
                                    .addComponent(btn_Coffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 790, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Card_DrinksLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_ChocDrink, btn_Coffee, btn_FountainDrinks, btn_Lemonade, btn_Milkshake, btn_SweetTea});

        Card_DrinksLayout.setVerticalGroup(
            Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_DrinksLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_DrinksMenu)
                .addGap(18, 18, 18)
                .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_FountainDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Milkshake, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_Coffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Card_DrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SweetTea, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(btn_ChocDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Lemonade))
                .addGap(111, 111, 111)
                .addComponent(Panel_DrinkSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Card_DrinksLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_ChocDrink, btn_Coffee, btn_FountainDrinks, btn_Lemonade, btn_Milkshake, btn_SweetTea});

        Panel_Cards.add(Card_Drinks, "card6");

        Card_Extras.setBackground(new java.awt.Color(255, 255, 204));
        Card_Extras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Extras");

        javax.swing.GroupLayout Card_ExtrasLayout = new javax.swing.GroupLayout(Card_Extras);
        Card_Extras.setLayout(Card_ExtrasLayout);
        Card_ExtrasLayout.setHorizontalGroup(
            Card_ExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_ExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(1445, Short.MAX_VALUE))
        );
        Card_ExtrasLayout.setVerticalGroup(
            Card_ExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_ExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(791, Short.MAX_VALUE))
        );

        Panel_Cards.add(Card_Extras, "card5");

        Card_CheckOut.setBackground(new java.awt.Color(51, 0, 153));
        Card_CheckOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Checkout:");

        btn_Debit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Debit.setText("Debit");
        btn_Debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DebitActionPerformed(evt);
            }
        });

        btn_GiftCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_GiftCard.setText("Gift Card");
        btn_GiftCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GiftCardActionPerformed(evt);
            }
        });

        btn_Credit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Credit.setText("Credit");
        btn_Credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreditActionPerformed(evt);
            }
        });

        btn_Cash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Cash.setText("Cash");
        btn_Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Debit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_Credit)
                        .addGap(40, 40, 40)
                        .addComponent(btn_Cash))
                    .addComponent(btn_GiftCard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Cash, btn_Credit, btn_Debit, btn_GiftCard});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Credit)
                    .addComponent(btn_Cash)
                    .addComponent(btn_Debit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_GiftCard)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Cash, btn_Credit, btn_Debit, btn_GiftCard});

        javax.swing.GroupLayout Card_CheckOutLayout = new javax.swing.GroupLayout(Card_CheckOut);
        Card_CheckOut.setLayout(Card_CheckOutLayout);
        Card_CheckOutLayout.setHorizontalGroup(
            Card_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_CheckOutLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Card_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Card_CheckOutLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 1404, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Card_CheckOutLayout.setVerticalGroup(
            Card_CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_CheckOutLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Cards.add(Card_CheckOut, "card3");

        Card_Burgers.setBackground(new java.awt.Color(255, 255, 204));

        btn_item1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item1.setText("Item 1");
        btn_item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item1ActionPerformed(evt);
            }
        });

        btn_item2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item2.setText("Item 2");
        btn_item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item2ActionPerformed(evt);
            }
        });

        btn_item3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item3.setText("Item 3");
        btn_item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item3ActionPerformed(evt);
            }
        });

        btn_item7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item7.setText("Item 7");
        btn_item7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item7ActionPerformed(evt);
            }
        });

        btn_item6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item6.setText("Item 6");
        btn_item6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item6ActionPerformed(evt);
            }
        });

        btn_item4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item4.setText("Item 4");
        btn_item4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item4ActionPerformed(evt);
            }
        });

        btn_item5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_item5.setText("Item 5");
        btn_item5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_item5ActionPerformed(evt);
            }
        });

        lbl_Burgers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Burgers.setText("Burgers");

        javax.swing.GroupLayout Card_BurgersLayout = new javax.swing.GroupLayout(Card_Burgers);
        Card_Burgers.setLayout(Card_BurgersLayout);
        Card_BurgersLayout.setHorizontalGroup(
            Card_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_BurgersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Card_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Card_BurgersLayout.createSequentialGroup()
                        .addComponent(btn_item4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_item5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_item6))
                    .addGroup(Card_BurgersLayout.createSequentialGroup()
                        .addComponent(btn_item1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_item2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_item3))
                    .addComponent(btn_item7)
                    .addComponent(lbl_Burgers))
                .addContainerGap(951, Short.MAX_VALUE))
        );

        Card_BurgersLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_item1, btn_item2, btn_item3, btn_item4, btn_item5, btn_item6, btn_item7});

        Card_BurgersLayout.setVerticalGroup(
            Card_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card_BurgersLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbl_Burgers)
                .addGap(18, 18, 18)
                .addGroup(Card_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_item1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_item2)
                    .addComponent(btn_item3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Card_BurgersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_item4)
                    .addComponent(btn_item5)
                    .addComponent(btn_item6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_item7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Card_BurgersLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_item1, btn_item2, btn_item3, btn_item4, btn_item5, btn_item6, btn_item7});

        Panel_Cards.add(Card_Burgers, "card7");

        Panel_Parent.add(Panel_Cards, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 75, 1530, 840));

        Panel_Employee_works.setBackground(new java.awt.Color(204, 204, 255));
        Panel_Employee_works.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Employee_works.setLayout(new java.awt.GridLayout(1, 0));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton5.setText("ClockIn/ClockOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Panel_Employee_works.add(jButton5);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setText("Manager");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Panel_Employee_works.add(jButton4);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton6.setText("Online Orders");
        Panel_Employee_works.add(jButton6);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton7.setText("Admin");
        Panel_Employee_works.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Panel_Employee_works.add(jButton8);

        Panel_Parent.add(Panel_Employee_works, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1877, 70));

        list_Order.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Unicode MS", 0, 14))); // NOI18N
        list_Order.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        list_Order.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "<click menu >" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_Order);

        jButton11.setBackground(new java.awt.Color(204, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton11.setText("REMOVE ITEM");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 51, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Calculator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton11, jButton13});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton11, jButton13});

        Panel_Parent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 75, -1, 830));

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_FoodMenu);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_ExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExtrasActionPerformed
        // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_Extras);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_ExtrasActionPerformed

    private void btn_CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckoutActionPerformed
         // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_CheckOut);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_CheckoutActionPerformed

    private void btn_BurgersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BurgersActionPerformed
        // TODO add your handling code here:
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_Burgers);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_BurgersActionPerformed

    private void btn_SidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SidesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SidesActionPerformed

    private void btn_DrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DrinksActionPerformed
        // TODO add your handling code here:
        Panel_Cards.removeAll();
       Panel_Cards.add(Card_Drinks);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_DrinksActionPerformed

    private void btn_LemonadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LemonadeActionPerformed
        // TODO add your handling code here:
        model1.addElement("Lemonade");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_LemonadeActionPerformed

    private void btn_item6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item6ActionPerformed
        model1.addElement("Food Item #6");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_item6ActionPerformed

    private void btn_CreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreditActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(Card_FoodMenu, "Swipe your card");
        
    }//GEN-LAST:event_btn_CreditActionPerformed

    private void btn_FountainDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FountainDrinksActionPerformed
        // TODO add your handling code here:
        model1.addElement("DRINK");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_FountainDrinksActionPerformed

    private void btn_DebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DebitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(Card_FoodMenu, "Swipe your card");
    }//GEN-LAST:event_btn_DebitActionPerformed

    private void btn_CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CashActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(Card_FoodMenu, "Payment Received!");
    }//GEN-LAST:event_btn_CashActionPerformed

    private void btn_GiftCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GiftCardActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(Card_FoodMenu, "Enter number:");
    }//GEN-LAST:event_btn_GiftCardActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(Card_FoodMenu, "Do you want to CANCEL this Order?");
       
        
    }//GEN-LAST:event_jButton12ActionPerformed

    public View_POS(JPanel Card_Burgers, JPanel Card_CheckOut, JPanel Card_Drinks, JPanel Card_Extras, JPanel Card_FoodMenu, JPanel Panel_Background, JPanel Panel_Buttons, JPanel Panel_Cards, JPanel Panel_Employee_works, JPanel Panel_Parent, JButton btn_Burgers, JButton btn_Cash, JButton btn_Checkout, JButton btn_ChocDrink, JButton btn_Coffee, JButton btn_CokeDrinks, JButton btn_Credit, JButton btn_Debit, JButton btn_Drinks, JButton btn_Extras, JButton btn_GiftCard, JButton btn_KidsMenu, JButton btn_Lemonade, JButton btn_Menu, JButton btn_Milkshake, JButton btn_Sandwiches, JButton btn_Sides, JButton btn_SweetTea, JButton btn_Wings, JButton btn_Wraps, JButton btn_item1, JButton btn_item2, JButton btn_item3, JButton btn_item4, JButton btn_item5, JButton btn_item6, JButton btn_item7, JButton jButton11, JButton jButton12, JButton jButton13, JButton jButton4, JButton jButton5, JButton jButton6, JButton jButton7, JButton jButton8, JLabel jLabel1, JLabel jLabel3, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JLabel lbl_Burgers, JLabel lbl_DrinksMenu, JLabel lbl_FoodMenu, JList list_Order, JTextArea rtb_total) throws HeadlessException {
        this.Card_Burgers = Card_Burgers;
        this.Card_CheckOut = Card_CheckOut;
        this.Card_Drinks = Card_Drinks;
        this.Card_Extras = Card_Extras;
        this.Card_FoodMenu = Card_FoodMenu;
        this.Panel_Background = Panel_Background;
        this.Panel_Buttons = Panel_Buttons;
        this.Panel_Cards = Panel_Cards;
        this.Panel_Employee_works = Panel_Employee_works;
        this.Panel_Parent = Panel_Parent;
        this.btn_Burgers = btn_Burgers;
        this.btn_Cash = btn_Cash;
        this.btn_Checkout = btn_Checkout;
        this.btn_ChocDrink = btn_ChocDrink;
        this.btn_Coffee = btn_Coffee;
        this.btn_FountainDrinks = btn_CokeDrinks;
        this.btn_Credit = btn_Credit;
        this.btn_Debit = btn_Debit;
        this.btn_Drinks = btn_Drinks;
        this.btn_Extras = btn_Extras;
        this.btn_GiftCard = btn_GiftCard;
        this.btn_KidsMenu = btn_KidsMenu;
        this.btn_Lemonade = btn_Lemonade;
        this.btn_Menu = btn_Menu;
        this.btn_Milkshake = btn_Milkshake;
        this.btn_Sandwiches = btn_Sandwiches;
        this.btn_Sides = btn_Sides;
        this.btn_SweetTea = btn_SweetTea;
        this.btn_Wings = btn_Wings;
        this.btn_Wraps = btn_Wraps;
        this.btn_item1 = btn_item1;
        this.btn_item2 = btn_item2;
        this.btn_item3 = btn_item3;
        this.btn_item4 = btn_item4;
        this.btn_item5 = btn_item5;
        this.btn_item6 = btn_item6;
        this.btn_item7 = btn_item7;
        this.jButton11 = jButton11;
        this.jButton12 = jButton12;
        this.jButton13 = jButton13;
        this.jButton4 = jButton4;
        this.jButton5 = jButton5;
        this.jButton6 = jButton6;
        this.jButton7 = jButton7;
        this.jButton8 = jButton8;
        this.jLabel1 = jLabel1;
        this.jLabel3 = jLabel3;
       
        this.jScrollPane2 = jScrollPane2;
        this.lbl_Burgers = lbl_Burgers;
        this.lbl_DrinksMenu = lbl_DrinksMenu;
        this.lbl_FoodMenu = lbl_FoodMenu;
        this.list_Order = list_Order;
        
    }

    DefaultListModel  model1= new DefaultListModel();
    private void btn_item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item1ActionPerformed
        // TODO add your handling code here:
        model1.addElement("Food Item #1");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
       
    }//GEN-LAST:event_btn_item1ActionPerformed

    private void btn_item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item2ActionPerformed
        // TODO add your handling code here:
        model1.addElement("Food Item #2");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_item2ActionPerformed

    private void btn_item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item3ActionPerformed
        // TODO add your handling code here:
         model1.addElement("Food Item #3");
         list_Order.setModel(model1);
         list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_item3ActionPerformed

    private void btn_item4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item4ActionPerformed
        // TODO add your handling code here:
        model1.addElement("Food Item #4");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_item4ActionPerformed

    private void btn_item5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item5ActionPerformed
        // TODO add your handling code here:
        model1.addElement("Food Item #5");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_item5ActionPerformed

    private void btn_item7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_item7ActionPerformed
        // TODO add your handling code here:
        model1.addElement("Food Item #7");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_item7ActionPerformed

    private void btn_MilkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MilkshakeActionPerformed
        // TODO add your handling code here:
        model1.addElement("Milkshake");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_MilkshakeActionPerformed

    private void btn_CoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CoffeeActionPerformed
        // TODO add your handling code here:
        model1.addElement("Coffee");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_CoffeeActionPerformed

    private void btn_SweetTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SweetTeaActionPerformed
        // TODO add your handling code here:
        model1.addElement("Sweet Tea");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_SweetTeaActionPerformed

    private void btn_ChocDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChocDrinkActionPerformed
        // TODO add your handling code here:
        model1.addElement("CHOC DRINK");
        list_Order.setModel(model1);
        list_Order.setSelectedIndex(0);
    }//GEN-LAST:event_btn_ChocDrinkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        model1.remove(list_Order.getSelectedIndex());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        View_Login mgrLogin = new View_Login();
        mgrLogin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        View_Emp_Verification empLogin = new View_Emp_Verification();
        empLogin.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed
                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card_Admin;
    private javax.swing.JPanel Card_Burgers;
    private javax.swing.JPanel Card_CheckOut;
    private javax.swing.JPanel Card_Drinks;
    private javax.swing.JPanel Card_Extras;
    private javax.swing.JPanel Card_FoodMenu;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Buttons;
    private javax.swing.JPanel Panel_Cards;
    private javax.swing.JPanel Panel_DrinkSize;
    private javax.swing.JPanel Panel_Employee_works;
    private javax.swing.JPanel Panel_Parent;
    private javax.swing.JButton btn_Burgers;
    private javax.swing.JButton btn_Cash;
    private javax.swing.JButton btn_Checkout;
    private javax.swing.JButton btn_ChocDrink;
    private javax.swing.JButton btn_Coffee;
    private javax.swing.JButton btn_Credit;
    private javax.swing.JButton btn_Debit;
    private javax.swing.JButton btn_Drinks;
    private javax.swing.JButton btn_Extras;
    private javax.swing.JButton btn_FountainDrinks;
    private javax.swing.JButton btn_GiftCard;
    private javax.swing.JButton btn_KidsMenu;
    private javax.swing.JButton btn_Lemonade;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Milkshake;
    private javax.swing.JButton btn_Sandwiches;
    private javax.swing.JButton btn_Sides;
    private javax.swing.JButton btn_SweetTea;
    private javax.swing.JButton btn_Wings;
    private javax.swing.JButton btn_Wraps;
    private javax.swing.JButton btn_item1;
    private javax.swing.JButton btn_item2;
    private javax.swing.JButton btn_item3;
    private javax.swing.JButton btn_item4;
    private javax.swing.JButton btn_item5;
    private javax.swing.JButton btn_item6;
    private javax.swing.JButton btn_item7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Burgers;
    private javax.swing.JLabel lbl_DrinksMenu;
    private javax.swing.JLabel lbl_FoodMenu;
    private javax.swing.JList list_Order;
    // End of variables declaration//GEN-END:variables
}
