/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos_software_systems;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Jovy
 */
public class View_Manager extends javax.swing.JFrame {

    /**
     * Creates new form View_Manager
     */
    public View_Manager() {
        initComponents();
        
        //Automatically adjusts the system's maximum screen size
        Toolkit centerWindowTool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(centerWindowTool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setSize(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mgr_BackgroundPanel = new javax.swing.JPanel();
        Mgr_Parent_Panel = new javax.swing.JPanel();
        Mgr_ButtonManager = new javax.swing.JPanel();
        Mgr_btn_reports = new javax.swing.JButton();
        Mgr_btn_EmpHours = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Mgr_ParentPanel_Card = new javax.swing.JPanel();
        Mgr_Card_Reports = new javax.swing.JPanel();
        Mgr_Card_EmpHours = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mgr_BackgroundPanel.setBackground(new java.awt.Color(51, 0, 153));

        Mgr_ButtonManager.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Mgr_btn_reports.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Mgr_btn_reports.setText("Reports");
        Mgr_btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mgr_btn_reportsActionPerformed(evt);
            }
        });

        Mgr_btn_EmpHours.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Mgr_btn_EmpHours.setText("Employee Hours");
        Mgr_btn_EmpHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mgr_btn_EmpHoursActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("jButton3");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setText("Return to MAIN VIEW");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Mgr_ButtonManagerLayout = new javax.swing.GroupLayout(Mgr_ButtonManager);
        Mgr_ButtonManager.setLayout(Mgr_ButtonManagerLayout);
        Mgr_ButtonManagerLayout.setHorizontalGroup(
            Mgr_ButtonManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mgr_ButtonManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mgr_btn_reports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mgr_btn_EmpHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Mgr_ButtonManagerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Mgr_btn_EmpHours, Mgr_btn_reports, jButton3, jButton7});

        Mgr_ButtonManagerLayout.setVerticalGroup(
            Mgr_ButtonManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mgr_ButtonManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mgr_ButtonManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mgr_btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Mgr_ButtonManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Mgr_btn_EmpHours)
                        .addComponent(jButton3)
                        .addComponent(jButton7)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Mgr_ButtonManagerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Mgr_btn_EmpHours, Mgr_btn_reports, jButton3, jButton7});

        Mgr_ParentPanel_Card.setLayout(new java.awt.CardLayout());

        Mgr_Card_Reports.setBackground(new java.awt.Color(255, 255, 204));
        Mgr_Card_Reports.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        javax.swing.GroupLayout Mgr_Card_ReportsLayout = new javax.swing.GroupLayout(Mgr_Card_Reports);
        Mgr_Card_Reports.setLayout(Mgr_Card_ReportsLayout);
        Mgr_Card_ReportsLayout.setHorizontalGroup(
            Mgr_Card_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        Mgr_Card_ReportsLayout.setVerticalGroup(
            Mgr_Card_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        Mgr_ParentPanel_Card.add(Mgr_Card_Reports, "card2");

        Mgr_Card_EmpHours.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Hours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        javax.swing.GroupLayout Mgr_Card_EmpHoursLayout = new javax.swing.GroupLayout(Mgr_Card_EmpHours);
        Mgr_Card_EmpHours.setLayout(Mgr_Card_EmpHoursLayout);
        Mgr_Card_EmpHoursLayout.setHorizontalGroup(
            Mgr_Card_EmpHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        Mgr_Card_EmpHoursLayout.setVerticalGroup(
            Mgr_Card_EmpHoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        Mgr_ParentPanel_Card.add(Mgr_Card_EmpHours, "card3");

        javax.swing.GroupLayout Mgr_Parent_PanelLayout = new javax.swing.GroupLayout(Mgr_Parent_Panel);
        Mgr_Parent_Panel.setLayout(Mgr_Parent_PanelLayout);
        Mgr_Parent_PanelLayout.setHorizontalGroup(
            Mgr_Parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mgr_Parent_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mgr_Parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mgr_ButtonManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mgr_ParentPanel_Card, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        Mgr_Parent_PanelLayout.setVerticalGroup(
            Mgr_Parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mgr_Parent_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mgr_ParentPanel_Card, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mgr_ButtonManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Mgr_BackgroundPanelLayout = new javax.swing.GroupLayout(Mgr_BackgroundPanel);
        Mgr_BackgroundPanel.setLayout(Mgr_BackgroundPanelLayout);
        Mgr_BackgroundPanelLayout.setHorizontalGroup(
            Mgr_BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mgr_BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mgr_Parent_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Mgr_BackgroundPanelLayout.setVerticalGroup(
            Mgr_BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mgr_BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mgr_Parent_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mgr_BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mgr_BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        View_POS posView = new View_POS();
        posView.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Mgr_btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mgr_btn_reportsActionPerformed
        // TODO add your handling code here:
        Mgr_ParentPanel_Card.removeAll();
       Mgr_ParentPanel_Card.add(Mgr_Card_Reports);
       Mgr_ParentPanel_Card.repaint();
       Mgr_ParentPanel_Card.revalidate();
    }//GEN-LAST:event_Mgr_btn_reportsActionPerformed

    private void Mgr_btn_EmpHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mgr_btn_EmpHoursActionPerformed
        // TODO add your handling code here:
         Mgr_ParentPanel_Card.removeAll();
       Mgr_ParentPanel_Card.add(Mgr_Card_EmpHours);
       Mgr_ParentPanel_Card.repaint();
       Mgr_ParentPanel_Card.revalidate();
    }//GEN-LAST:event_Mgr_btn_EmpHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mgr_BackgroundPanel;
    private javax.swing.JPanel Mgr_ButtonManager;
    private javax.swing.JPanel Mgr_Card_EmpHours;
    private javax.swing.JPanel Mgr_Card_Reports;
    private javax.swing.JPanel Mgr_ParentPanel_Card;
    private javax.swing.JPanel Mgr_Parent_Panel;
    private javax.swing.JButton Mgr_btn_EmpHours;
    private javax.swing.JButton Mgr_btn_reports;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
