/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos_software_systems;

/**
 *
 * @author Jovy
 */
public class View_POS extends javax.swing.JFrame {

    /**
     * Creates new form View_POS
     */
    public View_POS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Background = new javax.swing.JPanel();
        Panel_Parent = new javax.swing.JPanel();
        Panel_Buttons = new javax.swing.JPanel();
        btn_Menu = new javax.swing.JButton();
        btn_Extras = new javax.swing.JButton();
        btn_OrderReview = new javax.swing.JButton();
        btn_Checkout = new javax.swing.JButton();
        Panel_Cards = new javax.swing.JPanel();
        Card_Menu = new javax.swing.JPanel();
        Card_Extras = new javax.swing.JPanel();
        Card_OrderReview = new javax.swing.JPanel();
        Card_CheckOut = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Panel_Employee_works = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Background.setBackground(new java.awt.Color(102, 153, 255));

        Panel_Parent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Panel_Buttons.setBackground(new java.awt.Color(51, 0, 153));
        Panel_Buttons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_Menu.setText("Menu");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        Panel_Buttons.add(btn_Menu);

        btn_Extras.setText("Extras");
        btn_Extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExtrasActionPerformed(evt);
            }
        });
        Panel_Buttons.add(btn_Extras);

        btn_OrderReview.setText("Review Order");
        btn_OrderReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderReviewActionPerformed(evt);
            }
        });
        Panel_Buttons.add(btn_OrderReview);

        btn_Checkout.setText("Checkout");
        btn_Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckoutActionPerformed(evt);
            }
        });
        Panel_Buttons.add(btn_Checkout);

        Panel_Cards.setBackground(new java.awt.Color(0, 153, 102));
        Panel_Cards.setLayout(new java.awt.CardLayout());

        Card_Menu.setBackground(new java.awt.Color(255, 153, 255));
        Card_Menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Card_MenuLayout = new javax.swing.GroupLayout(Card_Menu);
        Card_Menu.setLayout(Card_MenuLayout);
        Card_MenuLayout.setHorizontalGroup(
            Card_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        Card_MenuLayout.setVerticalGroup(
            Card_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        Panel_Cards.add(Card_Menu, "card4");

        Card_Extras.setBackground(new java.awt.Color(255, 153, 51));
        Card_Extras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Card_ExtrasLayout = new javax.swing.GroupLayout(Card_Extras);
        Card_Extras.setLayout(Card_ExtrasLayout);
        Card_ExtrasLayout.setHorizontalGroup(
            Card_ExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        Card_ExtrasLayout.setVerticalGroup(
            Card_ExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        Panel_Cards.add(Card_Extras, "card5");

        Card_OrderReview.setBackground(new java.awt.Color(255, 255, 153));
        Card_OrderReview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Card_OrderReviewLayout = new javax.swing.GroupLayout(Card_OrderReview);
        Card_OrderReview.setLayout(Card_OrderReviewLayout);
        Card_OrderReviewLayout.setHorizontalGroup(
            Card_OrderReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        Card_OrderReviewLayout.setVerticalGroup(
            Card_OrderReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        Panel_Cards.add(Card_OrderReview, "card2");

        Card_CheckOut.setBackground(new java.awt.Color(0, 255, 255));
        Card_CheckOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Card_CheckOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        Card_CheckOut.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel1.setText("jLabel1");
        Card_CheckOut.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Panel_Cards.add(Card_CheckOut, "card3");

        Panel_Employee_works.setBackground(new java.awt.Color(255, 0, 102));
        Panel_Employee_works.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton4.setText("jButton4");
        Panel_Employee_works.add(jButton4);

        jButton5.setText("jButton5");
        Panel_Employee_works.add(jButton5);

        jButton6.setText("jButton6");
        Panel_Employee_works.add(jButton6);

        jButton7.setText("jButton7");
        Panel_Employee_works.add(jButton7);

        jButton8.setText("jButton8");
        Panel_Employee_works.add(jButton8);

        jButton9.setText("jButton9");
        Panel_Employee_works.add(jButton9);

        javax.swing.GroupLayout Panel_ParentLayout = new javax.swing.GroupLayout(Panel_Parent);
        Panel_Parent.setLayout(Panel_ParentLayout);
        Panel_ParentLayout.setHorizontalGroup(
            Panel_ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Employee_works, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_ParentLayout.setVerticalGroup(
            Panel_ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Employee_works, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Cards, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_BackgroundLayout = new javax.swing.GroupLayout(Panel_Background);
        Panel_Background.setLayout(Panel_BackgroundLayout);
        Panel_BackgroundLayout.setHorizontalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_BackgroundLayout.setVerticalGroup(
            Panel_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_Menu);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_ExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExtrasActionPerformed
        // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_Extras);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_ExtrasActionPerformed

    private void btn_OrderReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderReviewActionPerformed
         // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_OrderReview);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_OrderReviewActionPerformed

    private void btn_CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckoutActionPerformed
         // This is the code how you change the cards
       Panel_Cards.removeAll();
       Panel_Cards.add(Card_CheckOut);
       Panel_Cards.repaint();
       Panel_Cards.revalidate();
    }//GEN-LAST:event_btn_CheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card_CheckOut;
    private javax.swing.JPanel Card_Extras;
    private javax.swing.JPanel Card_Menu;
    private javax.swing.JPanel Card_OrderReview;
    private javax.swing.JPanel Panel_Background;
    private javax.swing.JPanel Panel_Buttons;
    private javax.swing.JPanel Panel_Cards;
    private javax.swing.JPanel Panel_Employee_works;
    private javax.swing.JPanel Panel_Parent;
    private javax.swing.JButton btn_Checkout;
    private javax.swing.JButton btn_Extras;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_OrderReview;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
